[fed]
name = "Galactic Federation"
motto = "For the galaxy and beyond!"
description = """One of the eldest surviving factions, and a general Federation of most
species, trying for equality.

Initially founded in 2153 after the researchers, mercenaries and engineers got tired of land
politics affected life in space, with the first Federation rally happening in the same year."""
quote = "The Federation is great, great at both keeping peace and failing to."
allies = "rcon,botani"
enemies = "hunion,soviet,pirates,tauri,soviet,heir"

[heir]
name = "The Heir"
motto = "The Federation is soon to die, and we are next in line."
quote = "Now the Heir doesn't believe in the Federation, nor genocide."
allies = "botani,rcon"
enemies = "hunion,heir,soviet,pirates"
description = ""

[hunion]
name = "Human Union"
motto = "For we are the first to discover, and we will not be the last!"
quote = ""
description = "A massive group of human supremacists believing that humans deserve the universe."
allies = "tauri,soviet"
enemies = "rcon,botani,pirates"

[soviet]
name = "Soviet V"
motto = "Fifth times the charm!"
quote = ""
description = "The fifth attempt at the Soviet Union."
allies = "hunion"
enemies = "fed,heir,pirates"

[rcon]
name = "Roach Conglomerate"
motto = "Cock in our name, roaches up your ass!"
quote = ""
description = "A faction representing and comprising of only roaches."
allies = "fed"
enemies = "pirates,hunion"

[botani]
name = "Botani Union"
motto = "We love plants."
quote = "Great plant produce producer, horrible war fighter."
description = "A union of multiple plant-based organisms under one name."
allies = "fed"
enemies = "pirates,hunion"

# general
[pirates]
name = "Pirates"
motto = "Don't care who or what you are, we have come for your booty!"
quote = "I hate them."
description = "Not really one *unified* faction but rather a Syndicate of bandits, thieves, smugglers, pirates, mercenaries and more."
enemies = "*"
allies = ""

# companies
[tauri]
name = "Tauri Corporation"
motto = "To the stars we fly!"
quote = "Developer of me, the AI. I may be biased but I think they're cool."
description = "One of the few surviving Earth companies, developing robotic technology and researching rapidly."
allies = "hunion"
enemies = "fed,pirates"
