# beam
[beam_one]
name = "Beam I"
description = "The first rendition of the Beam laser."
pierces_shields = false
uses_missiles = false

hull_damage = 3
oxygen_damage = 0
power_usage = 1

[beam_two]
name = "Beam II"
description = "The second rendition of the Beam laser."
pierces_shields = false
uses_missiles = false

hull_damage = 5
oxygen_damage = 2
power_usage = 2

[beam_three]
name = "Beam III"
description = "The final rendition of the Beam laser. Stronger than ever."
pierces_shields = false
uses_missiles = false

hull_damage = 8
oxygen_damage = 3
power_usage = 1

# missile
[launcha_one]
name = "Launcha I"
description = "An old piece of tech missile launcher made by Tauri in the early space age."
pierces_shields = true
uses_missiles = true

hull_damage = 3
oxygen_damage = 0
power_usage = 1

[launcha_two]
name = "Launcha II"
description = "An old piece of tech missile launcher made by Tauri in the early space age."
pierces_shields = true
uses_missiles = true

hull_damage = 3
oxygen_damage = 0
power_usage = 1
