[human]
single = "Human"
plural = "Humans"
description = "Humans are boring and uninteresting."

[fungi]
single = "Fungus"
plural = "Fungi"
description = "Fungi-like organisms on a widespread scale. Heat can kill them easily."

[borg]
single = "Borg"
plural = "Borgs"
description = "Robotic creatures created by humans. Made out of metal and wiring, weak to Ions."

[felinids]
single = "Felinid"
plural = "Felinids"
description = "A genetic distortion of humans due to failed cloning technology. Catgirls, otherwise identical to humans."

[spirit]
single = "Revenant"
plural = "Revanats"
description = "Half ghost half mortal creatures, they're like humans except they can phase through walls. Can still die to space."

[warblers]
single = "Warblenaut"
plural = "Warblers"
description = "Anomalous-like entities stretching everything around them (visually) and corrupting systems temporarily. Can die to every weapon quickly."

[autho]
single = "Auth"
plural = "Autho"
description = "Borgs with built in mind control, allowing them to swap minds for a minute at max."

[roach]
single = "Roach"
plural = "Roaches"
description = "Big roaches, sentient too. Like humans, but can spit out infectious spit and acid."

[avian]
single = "Avian"
plural = "Avians"
description = "Small bird-like creatures. Like humans, but can fly. And in some cases, may be possessed by their so called 'Allfather'."

[arachnid]
single = "Arachnid"
plural = "Arachnids"
description = "Half-human half-spider, with 8 legs. Faster and can make webs slowing prey."

[nano]
single = "Nano"
plural = "Nanni"
description = "Atom-sized organic nanobots colored skin with the ability to morph into anything, with every nanobot in a hivemind. Brittle."

[lizard]
single = "Lizard"
plural = "Lizards"
description = "Big and scaly, varies in color. They can regenerate limbs within minutes. Cannot stand the cold." 

[ai]
single = "AI"
plural = "AI"
description = "Sentient lifeforms trapped in an IBM piece of shit machine. Controls your whole ship, but has a codeword to deactivate."

[orc]
single = "Orc"
plural = "Orcs"
description = "Big, brutish, and very unpleasant. The orcs have quite the name for being great warriors."

[god]
single = "God"
plural = "Gods"
description = "A supreme being or deity. Immortal but not Invulenrable, possesses strength beyond any regular humans."

[syga]
single = "Syga"
plural = "Sygas"
description = "Life forms that can be composed of a variety of gasses. Gasses can be used in every which way they want to."

[thornling]
single = "Thornling"
plural = "Thornlings"
description = "Spiky, and rough skinned. Hunchbacks with spikes on their, in which can be used to their advantage."

[husk]
single = "Husk"
plural = "Husks"
description = "Living remains of what used to be human. Cannot feel pain, immunity to most diseases, and may act irrational."

[axolotl]
single = "Axolotl"
plural = "Axolotls"
description = "Cute marine animal. Can breathe underwater, and swim very fast."

[elem]
single = "elem"
plural = "elems"
description = "Humanoid-like creatures made of elements, whether that be pure fire or pure ice. Weakness depend on their element."
